# Generated by Django 6.0.2 on 2026-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.IntegerField(default=5),
        ),
    ]
